openapi: 3.0.3
info:
  title: Google Maps Platform
  description: API Specification for Google Maps Platform
  version: 1.17.2
servers:
  - url: 'https://api.worldpop.org/v1'
paths:
  /services/stats:
    get:
      tags:
        - services
      parameters:
        - name: dataset
          in: query
          schema:
            type: string
            enum:
              - wpgppop
              - wpgpas
          required: true
        - name: year
          in: query
          schema:
            type: integer
            minimum: 2010
          required: true
        - name: geojson
          in: query
          schema:
            $ref: '#/components/schemas/geoJson'
          required: true
        - name: key
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statsResponse'
              examples:
                Created:
                  value:
                    status: 'created'
                    status_code: 200
                    error: false
                    error_message: null
                    taskid: 'ed53cf88-a6c4-5ad2-968c-93775c480661'
  /tasks/{taskId}:
    get:
      tags:
        - tasks
      parameters:
        - name: taskId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tasksResponse'
              examples:
                Finished:
                  value:
                    status: "finished"
                    status_code: 200
                    error: false
                    error_message: null
                    data:
                      total_population: 1705754.5
                    taskid: "ee2e98e9-b9ea-5eb6-9c26-ecb8cb3469a3"
                    startTime: "2019-10-16 10:26:03.396803"
                    endTime: "2019-10-16 10:26:04.447173"
                    executionTime: 1

components:
  schemas:
    geoJson:
      title: GeoJson
      type: object
      description: https://geojson.org/
      required:
        - type
        - features
      properties:
        type:
          type: string
          enum:
            - FeatureCollection
        features:
          type: array
          items:
            type: object
            required:
              - type
              - geometry
            properties:
              type:
                type: string
                enum:
                  - Feature
              geometry:
                $ref: '#/components/schemas/geometryObject'
    geometryObject:
      type: object
      required:
        - type
        - coordinates
      properties:
        type:
          type: string
          enum:
            - Polygon
        coordinates:
          type: array
          items:
            type: array
            items:
              type: number
    statsResponse:
      type: object
      required:
        - status
        - status_code
        - error
        - taskid
      properties:
        status:
          type: string
        status_code:
          type: integer
        error:
          type: boolean
        error_message:
          type: string
          nullable: true
        taskid:
          type: string
    tasksResponse:
      type: object
      properties:
        status:
          type: string
        status_code:
          type: integer
        error:
          type: boolean
        error_message:
          type: string
        data:
          type: object
        taskid:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        executionTime:
          type: number
tags:
  - services
  - tasks
